config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/' => 'books#top', as: 'top'
  get '/users' => 'users#index'
  get '/books/about' => 'books#about'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :opinion, presence: true,length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true,length: { in: 2..20}
  validates :introduction,length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:top,:about]
	before_action :configure_permitted_parameters, if: :devise_controller?, except: [:top,:about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    top_path
  end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


	def top
	end

	def about
	end

	def new
		@book = Book.new

	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if   @book.save
			 flash[:notice] = "Book was successfully created."
			 redirect_to book_path(@book.id)
		else flash[:notice] = "ERROR!!"
  	      	 redirect_to user_path(current_user.id)
		end
	end

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@user = @book.user
		@book_new=Book.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user_id.to_i != current_user.id
        	flash[:notice] = "ERROR!!編集する権限がありません。"
        	redirect_to user_path(current_user.id)
   		end
	end

	def update
  		book = Book.find(params[:id])
  		book.update(book_params)
  		flash[:notice] = "Book was successfully updated."
  		redirect_to book_path(book.id)
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		flash[:notice] = "Book was successfully destroyed."
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :opinion)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books.reverse_order
    @book = Book.new

  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
       flash[:notice] = "ERROR!!編集する権限がありません。"
       redirect_to user_path(current_user.id)
      end
  end

  def update
  	@user = User.find(params[:id])
  	if    @user.update(user_params)
          flash[:notice] = "User was successfully updated."
  	      redirect_to books_path(@user.id)
    else  render 'edit'
    end
  end

private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-xs-3">
	<div class="profile-container">
	<h2 class="profile-name">User info</h2>

	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
	<table class="table">
		<tbody>
			<tr>
				<th>name</th>
				<th><%= user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= user.introduction %></th>
			</tr>
		</tbody>
	</table>
	</div>



	<div class="row">
		<% if user.id == current_user.id %>

		<p><%= link_to "",edit_user_path(user),class:"edit_user_#{user.id} col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
		<% end %>
	</div>

	<div class="field row">
	<h2>New book</h2>
	<%= form_for(book) do |f| %>

	<div class="field row">
	<lavel>Title</lavel>
	<%= f.text_field :title, class:"book_title col-xs-12 book_title" %>
	</div>

	<div class="field row">
	<lavel>Opinion</lavel>
	<%= f.text_area :opinion, class:"book_body col-xs-12 book_opinion" %>
	</div>

	<br>
	<div class="action row">
	<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
	</div>
	<% end %>

	</div>
</div>

app/views/books/about.html.erb
<div class="body">
	<div class="container">
		<h1>Welcome to
			<span class="glyphicon glyphicon-book"></span>
			Bookers !</h1>
	</div>
</div>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h1>Editing Book</h1>

			<%= form_for(@book) do |f| %>
			<h4>Title</h4>
				<%= f.text_field :title,class:"col-xs-12 book_title" %>
			<h4>Opinion</h4>
				<%= f.text_area :opinion,class:"col-xs-12 book_body" %><br>

			<%= f.submit 'Update Book',class:"btn btn-primary col-xs-12" %><br>

			<%= link_to "Show", book_path(@book),class:"show_#{@book.id}" %>

			<%= link_to "Back",books_path,class:"back" %>

			<% end %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">


		<%= render 'books/list',user: @user,book: @book %>


		<div class="col-xs-9">
		<h1>Books</h1>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>User</th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
			</thead>
			<tbody>
			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user_id),class:"user_#{@user.id}" do %>
					<%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image.jpg", :size => "40x40" %>
					<% end %>
					</td>

				<td><%=link_to book.title,book_path(book.id),class:"book_#{book.id}" %></td>


				<td><%= book.opinion %></td>
			</tr>
			<% end %>
			</tbody>
		</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">

<%= render 'books/list', user: @user,book: @book_new %>


<div class="col-xs-9">
	<h1>Books detail</h1>
		<table class="table">
			<tbody>
				<tr>
					<td>
					<%= link_to user_path(@user.id) do %>
					<%= attachment_image_tag @user,:profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image.jpg", :size => "40x40" %>
					<% end %>
					</td>
					<td>
						<p>
						<%= @book.title %>
						</p>
					</td>
					<td>
						<p>
						<%= @book.opinion %>
						</p>
					</td>

					<% if @book.user == current_user %>
				<td><%= link_to "Edit", edit_book_path(@book),class:"edit_book_#{@book.id} btn-sm btn-success" %></td>

				<td><%= link_to "Destroy", book_path(@book),class:"destroy_book_#{@book.id} btn-sm btn-danger", method: :delete,data: { confirm: 'Are you sure?'} %></td>

				<% end %>

				</tr>
			</tbody>
		</table>
</div>

</div>
</div>

app/views/books/top.html.erb
	<div class="container">
		<div class="row">
			<div class="top-message col-md-offset-3 col-md-6">
				<h1>welcome to
					<span class="glyphicon glyphicon-book">
						<strong>Bookers</strong>!!
					</span>
				</h1>
				<p>In
					<span class="glyphicon glyphicon-book">
					</span>
					<strong>Bookers</strong>,
				</p>
				<p>you can share and exchange your opinions , inpressions , and emotions
				</p>
				<p> about various books!</p>
				<div class="btn-wrapper">
					<div class="row">
						<p>
							<%= link_to "Log in",new_user_session_path,class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
						</p>
					</div>
					<div class="row">
						<p>
							<%= link_to "Sign Up",new_user_registration_path,class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Bookers</title>
  </head>

<body>
<div class="header">
<div class="container col-xs-12">
<div class="navbar navbar-inverse col-xs-12">
    <nav class="nav navbar-nav navbar-left text-muted">
      <h3>Bookers</h3>
    </nav>
  <nav>
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">

    <% if user_signed_in? %>

        <li class="">
        <%= link_to " Home",user_path(current_user.id),class: "home glyphicon glyphicon-home" %>
        </li>

        <li class="">
          <%= link_to " Users",users_path,class: "users glyphicon glyphicon-user" %>
        </li>

        <li class="">
          <%= link_to " Books",books_path,class: "books glyphicon glyphicon-book" %>
        </li>

        <li class="">
          <%= link_to " Logout",destroy_user_session_path, method: :delete, class: "logout glyphicon glyphicon-log-out" %>
        </li>

    <% else %>

        <li>
          <%= link_to " Home",top_path, class: "home glyphicon glyphicon-home" %>
        </li>

        <li>
          <%= link_to " About",books_about_path, class: "about glyphicon glyphicon-link" %>
        </li>

        <li>
        <%= link_to " Sign Up",new_user_registration_path,class: "sign_up glyphicon glyphicon-edit" %>
        </li>

        <li>
          <%= link_to " Log in",new_user_session_path,class: "sign_in glyphicon glyphicon-log-in" %>
        </li>
    <% end %>
  </ul>
</nav>
</div>
</div>
</div>

<%= yield %>

<footer class="footer style-2">
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc
        </p>
      </div>
    </div>
  </div>
</footer>

</body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">


		<div class="col-xs-9">
		<h1>User info</h1>
			<% if @user.errors.any? %>
			<h2>ERROR!!</h2>
			<% end %>
		<%= form_for(@user) do |f| %>
		<div class="form-group has-icon">

			<label class="control-label sr-only">Name</label>
			<%= f.text_field :name, autofocus: true, class:"name", placeholder:"name" %>

			<div class="form-group has-icon">
				<div class="user-edit-image">
					<%= attachment_image_tag @user, :profile_image, :fill, 60,60, fallback: "no_image.jpg" %>
				</div>
				<label class="control-label sr-only">ProfileImage</label>
			<%= f.attachment_field :profile_image, class:"user_image", placeholder:"ProfileImage" %>
			</div>

			<label class="control-label sr-only">Introduction</label>
			<%= f.text_area :introduction, autofocus: true, class:"introduction" %><br>
			<%= f.submit "Update User", class:"" %>
			<% end %>

		</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">


		<%= render 'books/list',user: @user, book: @book %>


		<div class="col-xs-9">
		<h1>Users</h1>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Image</th>
					<th>Name</th>
					<th>Show</th>
				</tr>
			</thead>
			<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user,:profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image.jpg", :size => "40x40" %></td>
				<td><%= user.name %></td>

				<td><%= link_to "Show",user_path(user.id),class:"user_#{user.id}" %></td>
			</tr>
			<% end %>
			</tbody>
		</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">


		<%= render 'books/list', user: @user,book: @book %>


		<div class="col-xs-9">
		<h1>Books</h1>
		<table class="table table-striped">
			<thead>
				<tr>
					<th colspan="1"></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
			</thead>
			<tbody>
			<% @books.each do |book| %>
			<tr>
				<td><%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image.jpg", :size => "40x40" %></td>
				<td><%=link_to book.title,book_path(book.id),class:"book_#{book.id}" %></td>
				<td><%= book.opinion %></td>
			</tr>
			<% end %>
			</tbody>
		</table>
		</div>
	</div>
</div>